# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapp.proto\x12\x06mygrpc\",\n\x15\x43\x61lculateTotalRequest\x12\x13\n\x0bproduct_ids\x18\x01 \x03(\t\"-\n\x16\x43\x61lculateTotalResponse\x12\x13\n\x0btotal_price\x18\x01 \x01(\x01\"+\n\x15ProductDetailsRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\"D\n\x16ProductDetailsResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\r\n\x05stock\x18\x03 \x01(\x05\x32\xba\x01\n\x0eProductService\x12T\n\x13\x43\x61lculateTotalPrice\x12\x1d.mygrpc.CalculateTotalRequest\x1a\x1e.mygrpc.CalculateTotalResponse\x12R\n\x11GetProductDetails\x12\x1d.mygrpc.ProductDetailsRequest\x1a\x1e.mygrpc.ProductDetailsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CALCULATETOTALREQUEST']._serialized_start=21
  _globals['_CALCULATETOTALREQUEST']._serialized_end=65
  _globals['_CALCULATETOTALRESPONSE']._serialized_start=67
  _globals['_CALCULATETOTALRESPONSE']._serialized_end=112
  _globals['_PRODUCTDETAILSREQUEST']._serialized_start=114
  _globals['_PRODUCTDETAILSREQUEST']._serialized_end=157
  _globals['_PRODUCTDETAILSRESPONSE']._serialized_start=159
  _globals['_PRODUCTDETAILSRESPONSE']._serialized_end=227
  _globals['_PRODUCTSERVICE']._serialized_start=230
  _globals['_PRODUCTSERVICE']._serialized_end=416
# @@protoc_insertion_point(module_scope)
